quarkus.datasource.db-kind=mssql
quarkus.datasource.username=${AZURE_SQL_USERNAME}
quarkus.datasource.password=${AZURE_SQL_PASSWORD}
quarkus.datasource.jdbc.url=${AZURE_SQL_JDBC_URL}

quarkus.datasource.jdbc.min-size=1
quarkus.datasource.jdbc.max-size=10
quarkus.datasource.jdbc.acquisition-timeout=30S

quarkus.hibernate-orm.schema-management.strategy=none
quarkus.hibernate-orm.log.sql=false

# Se habilitará cuando existan migraciones compatibles con Azure SQL.
quarkus.flyway.active=false
quarkus.http.port=8888